// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/panggggg/order-service/pkg/entity"
	mock "github.com/stretchr/testify/mock"
)

// OrderAPI is an autogenerated mock type for the OrderAPI type
type OrderAPI struct {
	mock.Mock
}

// SaveOrder provides a mock function with given fields: order
func (_m *OrderAPI) SaveOrder(order entity.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderAPI creates a new instance of OrderAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderAPI {
	mock := &OrderAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
